config/routes.rb
AggregatorApp::Application.routes.draw do
  get "scouting_results/index"

  get "spotify/index"

  get "soundcloud/index"

  root :to => 'soundcloud#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/scouting_controller.rb
class ScoutingController < ApplicationController
  def index
  end
end

app/controllers/scouting_results_controller.rb
class ScoutingResultsController < ApplicationController
  def index
  end
end

app/controllers/soundcloud_controller.rb
class SoundcloudController < ApplicationController
  def index #search

  end

  def search
    # get params
    # hit api
    # send results to view page
  end

end

app/controllers/spotify_controller.rb
class SpotifyController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/scouting_helper.rb
module ScoutingHelper
end

app/helpers/scouting_results_helper.rb
module ScoutingResultsHelper
end

app/helpers/soundcloud_helper.rb
module SoundcloudHelper
end

app/helpers/spotify_helper.rb
module SpotifyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fitch tools</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header class="header">
  <h1>Band Scout</h1>
  <h2>Artist/Song Data Aggregator</h2>
</header>

<div class="header_links">
  <button>
    <%= link_to 'Soundcloud Charts', soundcloud_index_path %>
  </button>
  <button>
    <%= link_to 'Spotify Latest Playlist', spotify_index_path %>
  </button>
</div>
<br><hr>

<%= yield %>

</body>
</html>

app/views/scouting/index.html.erb
# this page may not really be needed

app/views/scouting_results/index.html.erb
<h1>Results!</h1>

app/views/soundcloud/index.html.erb
<h3>Soundcloud Chart Search</h3>
<div>
  <button>place holder for "Top 50" pull down menu</button>
  <button>place holder for "Chart" pull down menu</button>
</div>

<br>
<div>
  <button onclick="window.location.href='/scouting_results'">Hit Me!</button>
</div>

app/views/spotify/index.html.erb
<h3>Spotify Latest Playlist Search</h3>

<form action="demo_form.asp">
  Spotify User Name: <input type="text" name="spotify_user"><br><br>
  <input type="submit" value="Hit Me!">
</form>